# Generated by Django 5.0.6 on 2024-05-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsadmin',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lmsadmin',
            name='usename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
