# Generated by Django 5.0.6 on 2024-05-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0002_lmsadmin_password_lmsadmin_usename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lmsadmin',
            old_name='usename',
            new_name='username',
        ),
    ]
